export default {
  state: {
    rye_bread: [
      {
        id: 1,
        title: "«Земгальский»",
        title_color: "black",
        card_color: "lime lighten-4",
        description: "Десертный ржаной заварной хлеб с сухофруктами и орехами 500-550 г",
        composition: "мука ржаная обдирная, цельнозерновая, солод ржаной, кориандр молотый, изюм, курага, чернослив, грецкий орех",
        picture: "images/1-rye-bread/1-1-desertnyj-s-suhofruktami.webp",
      },
      {
        id: 2,
        title: "«Дарницкий»",
        title_color: "black",
        card_color: "lime lighten-4",
        description: "Ржано-пшеничный хлеб. Малый: 400-450 г, большой: 750-800 г",
        composition: "мука первого сорта, мука ржаная обдирная",
        picture: "images/1-rye-bread/1-2-darnickij.webp",
      },
      {
        id: 3,
        title: "«Ржаное чудо»",
        title_color: "black",
        card_color: "lime lighten-4",
        description: "Ржано-пшеничный заварной. Малый: 400-450 г, большой: 800-850 г",
        composition: "солод, мед, патока, молотый кориандр",
        picture: "images/1-rye-bread/1-3-rzhanoe-chudo.webp",
      },
      {
        id: 4,
        title: "«Альпийский»",
        title_color: "black",
        card_color: "lime lighten-4",
        description: "Пшенично-ржаной заварной, 500 г",
        composition: "мука ржаная обдирная, мука первого сорта, семена подсолнечника, морковь сушеная, ржаной солод",
        picture: "images/1-rye-bread/1-4-alpijskij.webp",
      },
    ],
    wheat_bread: [
      {
        id: 1,
        title: "«Французская булка»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Пшеничный хлеб со сливочным маслом. Малый: 400-450 г, большой: 800-900 г",
        composition: "пшеничная мука высшего сорта, сахар, сливочное масло",
        picture: "images/2-wheat-bread/2-1-francuzskaya-bulka.webp",
      },
      {
        id: 2,
        title: "«Тыквенный»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Пшеничный хлеб на тыквенном пюре. Малый: 400-450 г, большой: 800-950 г",
        composition: "пшеничная мука высшего и первого сорта, тыквенное пюре, сахар, семена чиа, льна и подсолнечника",
        picture: "images/2-wheat-bread/2-2_tykvennyj.webp",
      },
      {
        id: 3,
        title: "«Пшеничный»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Пшеничный хлеб, 650-700 г",
        composition: "мука первого сорта, цельнозерновая мука тонкого помола (по желанию с добавлением семян) или на миксе муки с добавлением полбяной, спельтовой или ржаной муки",
        picture: "images/2-wheat-bread/2-3-pshenichnyj.webp",
      },
      {
        id: 4,
        title: "«Хоккайдо»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Хлеб японский молочный «Хоккайдо». Малый: 300 г, большой: 500 г",
        composition: "мука высшего сорта, заварка на молоке, сухое молоко, яйцо",
        picture: "images/2-wheat-bread/2-4-hokkajdo.webp",
      },
      {
        id: 5,
        title: "«Тартин»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Пшеничный хлеб длительной холодной ферментации. Малый: 400-450 г, большой 900 г",
        composition: "мука пшеничная высшего сорта и цельнозерновая тонкого помола",
        picture: "images/2-wheat-bread/2-5-tartin.webp",
      },
      {
        id: 6,
        title: "«Прованс»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Пшеничный хлеб с вялеными помидорами и сыром, 900-950 г",
        composition: "мука пшеничная первого сорта, цельнозерновая, сыр, вяленые томаты, травы на выбор прованские, либо итальянские",
        picture: "images/2-wheat-bread/2-6-provans.webp",
      },
      {
        id: 7,
        title: "«Луковый»",
        title_color: "white",
        card_color: "orange accent-1",
        description: "Пшеничный хлеб с карамелизированным луком, 500 г",
        composition: "Пшеничная мука с добавлением цельнозерновых ржаной и пшеничной муки, карамелизированный (жареный) лук",
        picture: "images/2-wheat-bread/2-7-lukovyj.webp",
      },
    ],
    cookies: [
      {
        id: 1,
        title: "Печенье «Пряная тыква»",
        title_color: "black",
        card_color: "yellow lighten-3",
        description: "Печенье на тыквенном пюре с кусочками темного шоколада и грецким орехом",
        composition: "мука пшеничная высшего сорта, тыквенное пюре, темный шоколад, корица, кардамон, имбирь",
        picture: "images/3-cookies/3-1-pryanaya-tykva.webp",
      },
      {
        id: 2,
        title: "«Штоллен»",
        title_color: "white",
        card_color: "yellow lighten-3",
        description: "Немецкая рождественская выпечка с цукатами, марципаном и франжипаном",
        composition: "мука пшеничная, масло сливочное, молоко, яйцо, миндаль. Изюм, вяленая клюква, вишня и апельсиновые цукаты, вымоченные в коньяке",
        picture: "images/3-cookies/3-2-shtollen.webp",
      },
      {
        id: 3,
        title: "Печенье «Овсяно-шоколадное»",
        title_color: "white",
        card_color: "yellow lighten-3",
        description: "Овсяное печенье с алколизованным какао",
        composition: "мука пшеничная, овсяные хлопья, масло, какао, соль",
        picture: "images/3-cookies/3-3-ovsyano-shokoladnoe.webp",
      },
      {
        id: 4,
        title: "«Ромовая баба»",
        title_color: "white",
        card_color: "yellow lighten-3",
        description: "Сдобная выпечка с изюмом",
        composition: "мука пшеничная высшего сорта, масло, яйцо, изюм, сироп с коньяком",
        picture: "images/3-cookies/3-4-romovaya-baba.webp",
      },
      {
        id: 5,
        title: "«Шоколадная баба»",
        title_color: "black",
        card_color: "yellow lighten-3",
        description: "Сдобная выпечка с темным шоколадом",
        composition: "мука пшеничная высшего сорта, масло, мучная заварка, темный шоколад, какао, сахарный сироп, 450-500 г",
        picture: "images/3-cookies/3-5-shokoladnaya-baba.webp",
      },
    ],
  },

  mutations: {},

  actions: {},

  getters: {
    bakeryRyeGetter (state) {
      return state.rye_bread
    },
    bakeryWheatGetter (state) {
      return state.wheat_bread
    },
    bakeryCookiesGetter (state) {
      return state.cookies
    },
  },
}
